import "source-map-support/register";

const originalTranslationReplacements = [
  ["Uitkijktoren", "Kèkstègâh"],
  ["uitkijktoren", "kèkstègâh"],
  ["childerswijk", "childâhswijk"],
  ["eider", "èijâh"],
  ["(?<![o])ei", "è"],
  ["Ei", "È"],
  ["(B|b)roodje bal", "$1eschùitstùitâh"],
  ["koets", "patsâhbak"],
  ["kopje koffie", "bakkie pleuâh"],
  ["Kopje koffie", "Bakkie pleuâh"],
  ["koffie\\b", "pleuâh"],
  ["Koffie\\b", "Pleuâh"],
  ["Kurhaus", "Koeâhhâhs"],
  ["\\bMaurice\\b", "Mâhpie"],
  ["Hagenezen", "Hageneize"],
  ["toiletten", "pleis"],
  ["Toiletten", "Pleis"],
  ["toilet", "plei"],
  ["Toilet", "Plei"],
  ["(B|b)al gehakt", "$1eschùitstùitâh"],
  ["(N|n)erd", "$1euâhd"],
  ["(L|l)unchroom", "$1unsroem"],
  ["\\bThis\\b", "Dis"],
  ["design", "diesain"],
  ["\\b(H|h)ighlights\\b", "$1aailaaits"],
  ["\\b(L|l)ast-minute\\b", "$1asminnut"],
  ["\\bAirport", "Èâhpogt"],
  ["\\bairport", "èâhpogt"],
  ["(A|a)dvertentie", "$1dvâhtensie"],
  ["\\b(B|b)eauty", "$1joetie"],
  ["\\bthe\\b", "de"],
  ["\\b(B|b)east\\b", "$1ies"],
  ["(B|b)each", "$1ietsj"],
  ["Bites", "Bèts"],
  ["Cuisine", "Kwiesien"],
  ["cuisine", "kwiesien"],
  ["Europese", "Euraipeise"],
  ["(?<![z])event(s|)", "ievent$1"],
  ["Event(s|)", "Ievent$1"],
  ["(F|f)acebook", "$1eisboek"],
  ["(F|f)avorite", "$1avverietûh"],
  ["(F|f)avoriete", "$1avverietûh"],
  ["(F|f)lagship", "fleksjip"],
  ["Jazz", "Djes"],
  ["jazz", "djes"],
  ["(T|t)entoon", "$1etoon"],
  ["(C|c)abaret", "$1abberet"],
  ["(M|m)usical", "$1usikol"],
  ["kids", "kindâh"],
  ["(M|m)ovies", "$1oevies"],
  ["(?<![vZz])(O|o)r(i|)g", "$1âhg"],
  ["orige", "orage"],
  ["chine", "sjine"],
  ["(P|p)alace", "$1ellus"],
  ["(P|p)rivacy", "$1raaivesie"],
  ["policy", "pollesie"],
  ["\\b(R|r)oots\\b", "$1oets"],
  ["SEA LIFE", "SIELÈF"],
  ["(S|s)how", "$1jow"],
  ["(S|s)hoppen", "$1joppûh"],
  ["(S|s)kiën", "$1kieje"],
  ["(S|s)tores", "$1toâhs"],
  ["(T|t)ouchscreen", "$1atskrien"],
  ["(T|t)ouch", "$1ats"],
  ["that", "det"],
  ["(T|t)ripadvisor", "$1ripetfaaisoâh"],
  ["(V|v)andaag", "$1edaag"],
  ["\\b(V|v)erder\\b", "$1eâhdahs"],
  ["(V|v)intage", "$1intuts"],
  ["you(?![n])", "joe"],
  ["You(?![n])", "Joe"],
  ["(W|w)eekend", "$1iekend"],
  ["(W|w)ork", "$1urrek"],
  ["(B|b)ibliotheek", "$1iebeleteik"],
  ["(F|f)ood", "$1oet"],
  ["mondkapje", "bekbedekkâh"],
  ["Mondkapje", "Bekbedekkâh"],
  ["(D|d)evelop", "$1ievellep"],
  ["doe je het", "doejenut"],
  ["\\bsee\\b", "sie"],
  ["(M|n|R|r)ust(?![ai])", "$1us"],
  ["(M|m)oeten", "$1otte"],
  ["(w|W)eleens", "$1elles"],
  ["(g|G)ouv", "$1oev"],
  ["(H|h)eeft", "$1ep"],
  ["(on|i)der(?!e)", "$1dâh"],
  ["iendel", "iendâhl"],
  ["(?<![ao])ndere", "ndâhre"],
  ["uier\\b", "uiâh"],
  ["ui", "ùi"],
  ["Ui", "Ùi"],
  ["(?<![ieopfv])ert\\b", "egt"],
  ["pert\\b", "peâh"],
  ["\\b(V|v)ert", "$1et"],
  ["(?<![eo])erte", "egte"],
  ["(?<![eo])(a|o)r(|s)t(?!j)", "$1g$2t"],
  [" er aan", " d'ran"],
  ["(A|a)an het\\b", "$1nnut"],
  ["\\b(A|a)an", "$1n"],
  ["\\b(G|g)aan\\b", "$1an"],
  ["(H|h)oud\\b", "$1ou"],
  ["(B|b|R|r|P|p)ou(l|t)", "$1oe$2"],
  ["oele\\b", "oel"],
  ["(au|ou)w(?!e)", "$1"],
  ["oude", "ouwe"],
  ["\\b(T|t)our\\b", "$1oeâh"],
  ["diner\\b", "dinei"],
  ["o(e|u)r\\b", "oeâh"],
  ["oer(?![aieou])", "oeâh"],
  ["jour", "sjoeâh"],
  ["Jour", "Sjoeâh"],
  ["(?<![epYy])(au|ou)(?![v])", "âh"],
  ["Ou", "Âh"],
  ["aci", "assi"],
  ["als een", "assun"],
  ["a(t|l) ik", "a$1$1ik"],
  ["alk\\b", "alluk"],
  ["(?<![a])ars", "ags"],
  ["oor", "oâh"],
  ["(A|a)ar(?![io])", "$1ah"],
  ["aar(?![i])", "ar"],
  ["patie", "petie"],
  ["aagd\\b", "aag"],
  ["(am|at|ig|ig|it|kk|nn)en(?![ e,.?!])", "$1e"],
  ["\\b(K|k)an er\\b", "$1andâh"],
  ["\\b(K|k)en ik\\b", "$1ennik"],
  ["\\b(K|k)en u\\b", "$1ennu"],
  ["\\b(K|k)en jij\\b", "$1ejjèh"],
  ["\\b(A|a)ls u", "$1ssu"],
  ["\\b(M|m)ag het\\b", "$1aggut"],
  ["\\bik dacht het\\b", "dachut"],
  ["\\b(V|v)an jâh\\b", "$1ajjâh"],
  ["\\b(K|k)ijk dan\\b", "$1èktan"],
  ["\\b(G|g)aat het\\b", "$1aat-ie"],
  ["\\b(M|m)et je\\b", "$1ejje"],
  ["\\b(V|v)ind je\\b", "$1ijje"],
  ["\\bmij het\\b", "mènnut"],
  ["\\b(A|a)ls er\\b", "$1stâh"],
  ["\\b(K|k)(u|a)n j(e|ij) er\\b", "$1ejjedâh"],
  ["\\b(K|k)un je\\b", "$1ajje"],
  ["\\bje ([^ ]+) je", "je $1 je ège"],
  ["ADO Den Haag", "FC De Haag"],
  ["ADO", "Adau"],
  ["(?<![i])atie(?![fkv])", "asie"],
  ["avil", "ave"],
  ["sje\\b", "ssie"],
  ["\\balleen\\b", "enkelt"],
  ["\\bAlleen\\b", "Enkelt"],
  ["(A|a)ls je", "$1sje"],
  ["athe", "atte"],
  ["\\bApp", "Ep"],
  ["\\bapp", "ep"],
  ["(o|u)als\\b", "$1as"],
  ["(b|k|w)ar\\b", "$1âh"],
  ["\\b(A|a)ls\\b", "$1s"],
  [" bent\\b", " ben"],
  ["bote", "baute"],
  ["(B|b)roc", "$1rauc"],
  ["bt\\b", "b"],
  ["cce", "kse"],
  ["cc", "kk"],
  ["chique", "sjieke"],
  ["(?<![s])chure", "sjure"],
  ["pact", "pekt"],
  ["aca", "akke"],
  ["c(a|o|t|r)", "k$1"],
  ["C(a|o|t|r)", "K$1"],
  ["(c|k)or\\b", "$1oâh"],
  ["(?<![.])c(a|o)", "k$1"],
  ["\\bkoro", "kerau"],
  ["cu", "ku"],
  ["Cu", "Ku"],
  ["ci(ë|ee)l", "sjeil"],
  ["(ch|c|k)t\\b", "$1"],
  ["(ch|c|k)t(?![aeiouâr])", "$1"],
  ["(?<![Gg])(e|r)gt\\b", "$1g"],
  ["(d|D)at er", "$1attâh"],
  ["(d|D)at is ", "$1a's "],
  ["denst", "dest"],
  ["derb", "dâhb"],
  ["nderh", "ndâhh"],
  ["derd\\b", "dâhd"],
  ["(D|d)eze(?![l])", "$1eize"],
  ["dt\\b", "d"],
  ["\\b(B|b)ied\\b", "$1iedt"],
  ["(D|d)y", "$1i"],
  ["eaa", "eiaa"],
  ["(E|e)nig", "$1inag"],
  ["eau\\b", "o"],
  ["ègent", "èget"],
  ["Eig", "Èg"],
  ["eig", "èg"],
  ["uee\\b", "uwee"],
  ["ueel\\b", "eweil"],
  ["uele\\b", "eweile"],
  ["(g|n|l|L|m|M)ee(n|s)", "$1ei$2"],
  ["ee\\b", "ei"],
  ["eel", "eil"],
  [" is een ", " issun "],
  ["(I|i)n een ", "$1nnun "],
  ["één", "ein"],
  ["\\been\\b", "un"],
  ["\\bEen\\b", "Un"],
  [" eens", " 'ns"],
  ["(?<![eo])erd\\b", "egd"],
  ["eerd", "eâhd"],
  ["(?<![k])ee(d|f|g|k|l|m|n|p|s|t)", "ei$1"],
  ["(?<![l])ands\\b", "ens"],
  ["(?<![st])ain", "ein"],
  ["(?<![èijhmr])ds(?![ceèt])", "s"],
  ["(?<![eh])ens\\b", "es"],
  ["kens", "kes"],
  ["(D|d)ance", "$1ens"],
  ["(?<![ hi])eden\\b", "eije"],
  ["(?<![ bgi])eden", "eide"],
  ["\\b(E|e)ve", "$1ive"],
  ["(?<![a])(m|M|R|r)e(d|t|n)e(?![ei])", "$1ei$2e"],
  ["(G|g)ener", "$1einer"],
  ["(E|e)nerg", "$1inerg"],
  ["eugd", "eug"],
  ["(?<![o])epot\\b", "eipau"],
  ["(e|E)rg\\b", "$1rrag"],
  ["(?<![fnN])(a|o)rm", "$1rrem"],
  ["(f|N|n)orma", "$1oâhma"],
  ["(i|I|a|A)(l|n)terna", "$1$2tâhna"],
  ["elden", "elde"],
  ["oeter", "oetâh"],
  ["erm\\b", "errum"],
  ["(?<![ iegoptvV])er(m|n)", "erre$1"],
  ["(?<![edktv])(e|E)rg(?!ez|i)", "$1rreg"],
  ["(?<![i])(g|b)er(?![eoiuaâèr])", "$1âh"],
  ["epers\\b", "epâhs"],
  ["(P|p)ers(?![l])", "$1egs"],
  ["(K|k)erst", "$1egs"],
  ["(?<![e])(t|V|v)ers(?![clt])", "$1egs"],
  ["(G|g)eve(r|n)", "$1eive$2"],
  ["(t|w|W)ene", "$1eine"],
  ["renstr", "restr"],
  ["(?<![eIio])eder", "eider"],
  ["(?<![eiop])ers\\b", "âhs"],
  ["(H|h)er(?![erop])", "$1eâh"],
  ["\\b(K|k)ers", "$1egs"],
  ["\\b(T|t)ers", "$1es"],
  ["(?<![vVi])ers(c|t)", "âhs$1"],
  ["erwt", "erret"],
  ["(?<![eor])eci", "eici"],
  ["eserve(e|r)", "eiserve$1"],
  ["erve\\b", "erreve"],
  ["ervek", "errevek"],
  ["serv", "sev"],
  ["eiser", "eisâh"],
  ["eur\\b", "euâh"],
  ["eur(?![eio])", "euâh"],
  ["eur(i|o)", "euâhr$1"],
  ["eurl", "euâhl"],
  ["eer", "eâh"],
  ["elk\\b", "ellek"],
  ["(?<![og])ega", "eige"],
  ["(E|e)xt", "$1kst"],
  ["(H|h|n|T|t)ele(?![u])", "$1eile"],
  ["\\b(E|e)le", "$1ile"],
  ["ffis", "ffes"],
  ["(G|g)ese", "$1esei"],
  ["\\b(g|G|v|V)ele\\b", "$1eile"],
  ["ebut", "eibut"],
  ["\\b(D|d)elen", "$1eile"],
  ["sdelen", "sdeile"],
  ["(?<![diokrs])ele(n|m|r)", "eile$1"],
  ["(B|b)eke(?![n])", "$1eike"],
  ["(B|b)ene(?![v])", "$1eine"],
  ["(?<![ioBbg])eke(?![e])", "eike"],
  ["(?<![r])rege(?![r])", "reige"],
  ["(T|t)ege(?![l])", "$1eige"],
  ["(?<![bBIiort])e(g|v|p)e(l|n|m| )", "ei$1e$2"],
  ["(?<![e])dige", "dege"],
  ["(L|l)ever", "$1eiver"],
  ["alve\\b", "alleve"],
  ["\\b(K|k)en\\b", "$1an"],
  ["(a|o)ien\\b", "$1ie"],
  ["(?<![ bieo])en([.?!])", "ûh$1"],
  ["(?<![ ])ben([.?!])", "ûh$1"],
  ["(?<![ bieohr(])en\\b", "e"],
  ["(?<![r])ren\\b", "re"],
  ["bben\\b", "bbe"],
  ["oien\\b", "oie"],
  ["enso", "eso"],
  ["eum", "eijum"],
  ["(?<![eio])enm(?![e])", "em"],
  ["(?<![eiorRvV])en(b|h|j|l|p|r|v|w|z)", "e$1"],
  ["([Hh])eb je ", "$1ebbie "],
  ["(H|h)eb (un|een)\\b", "$1ep'n"],
  ["(?<![eu])eb\\b", "ep"],
  ["(E|e)x(c|k)", "$1ksk"],
  ["(?<![ s])teri", "tâhri"],
  ["(?<![ sS])ter(?![aeirnû])", "tâh"],
  ["sterd", "stâhd"],
  ["(F|f)eli", "$1eili"],
  ["(F|f)en(a|o)", "$1ein$2"],
  ["(I|i)ndeli", "$1ndeili"],
  ["(f|p)t\\b", "$1"],
  ["\\b(N|n)iet\\b", "$1ie"],
  ["fd(?![eo])", "f"],
  ["(F|f)eb", "$1eib"],
  ["ngt\\b", "nk"],
  ["(?<![o])e(k|v)ing", "ei$1ing"],
  ["gje\\b", "ggie"],
  ["go\\b", "gau"],
  ["go(r)", "gau$1"],
  ["gelegd\\b", "geleige"],
  ["([HhVvr])ee(l|n|t)", "$1ei$2"],
  ["(I|i)n het", "$1nnut"],
  ["(K|k)ete", "$1eite"],
  ["\\b(E|e)te", "$1ite"],
  ["(?<![ior])ete(?![il])", "eite"],
  ["(d|h|l|m|r|t)ea(?![m])", "$1eija"],
  ["\\bhet\\b", "ut"],
  ["Het\\b", "Ut"],
  ["(?<![eouù])i\\b", "ie"],
  ["ieri(n|g)", "ieâhri$1"],
  ["emier", "emjei"],
  ["(?<![uù])ier(?!(a|e|i|ony))", "ieâh"],
  ["iero(?!e|o|nd)", "ierau"],
  ["ière", "ijerre"],
  ["ibu", "ibe"],
  ["icke", "ikke"],
  ["iti(a|o|au)", "isi$1"],
  ["ijgt\\b", "ijg"],
  ["(B|b)ijz", "$1iez"],
  ["ij\\b", "è"],
  ["(?<![e])ije(?![ei])", "èje"],
  ["èjen", "èje"],
  ["(B|b)ij", "$1è"],
  ["\\blijk\\b", "lèk"],
  ["(D|d|K|k|p|R|r|W|w|Z|z)ijk", "$1èk"],
  ["ij([dgslmnftpvz])", "è$1"],
  ["edig", "eidag"],
  ["(?<![euù])ig\\b", "ag"],
  ["tigdù", "tagdù"],
  ["lige\\b", "lage"],
  ["(?<![euù])igd\\b", "ag"],
  ["\\bIJ", "È"],
  ["ilm", "illem"],
  ["ilieu", "ejui"],
  ["incia", "insja"],
  ["inc(k|)(?![i])", "ink"],
  ["io(?![oen])", "iau"],
  ["\\bin m'n\\b", "imme"],
  ["(n|r)atio", "$1asjau"],
  ["io\\b", "iau"],
  ["io(?![oen])", "iau"],
  ["ir(c|k)", "irrek"],
  ["(?<![gr])ties\\b", "sies"],
  ["oï", "aui"],
  ["isch(|e)", "ies$1"],
  ["is er", "istâh"],
  ["ap je\\b", "appie"],
  ["(p) je\\b", "$1ie"],
  ["(?<![i])(g|k) je\\b", "$1$1ie"],
  ["jene", "jenei"],
  ["jezelf", "je ège"],
  ["(?<![oe])kje\\b", "kkie"],
  ["olg", "olleg"],
  ["(a|i|o)(k|p)je\\b", "$1$2$2ie"],
  ["(?<![ deèijstn])je\\b", "ie"],
  ["(K|k)an\\b", "$1en"],
  ["(K|k)unne", "$1enne"],
  ["(K|k)unt", "$1en"],
  ["(K|k)led(?![d])", "$1leid"],
  ["\\bOra", "Aura"],
  ["\\bora", "aura"],
  ["orf", "orref"],
  ["oro(?![eo])", "orau"],
  ["Oo([igkm])", "Au$1"],
  ["oo([difgklmnpst])", "au$1"],
  ["lo\\b", "lau"],
  ["([RrNn])ij", "$1è"],
  ["tieg", "sieg"],
  ["(?<![e])tie\\b", "sie"],
  ["enties\\b", "ensies"],
  ["er(f|p)(?![a])", "erre$1"],
  ["(b|B|k|K|m|L|l|M|p|P|t|T|w|W)erk", "$1errek"],
  ["(f|k)jes\\b", "$1$1ies"],
  ["(M|m)'n", "$1e"],
  ["(M|m)ong", "$1eg"],
  ["k mein(?![ut])", "k meint"],
  ["mt\\b", "mp"],
  ["(?<![oO])md(?![e])", "mp"],
  ["lair(?![e])", "lèh"],
  ["ulaire", "elère"],
  ["lein", "lèn"],
  ["\\bliggûh\\b", "leggûh"],
  ["\\b(L|l)igge\\b", "$1egge"],
  ["\\b(L|l)igt\\b", "$1eg"],
  ["(?<![p])(L|l)ez", "$1eiz"],
  ["lf", "lluf"],
  ["ll([ ,.])", "l$1"],
  ["(a|e|i|o|u)rk\\b", "$1rrek"],
  ["(P|p)arke", "$1agke"],
  ["ark(?![a])", "arrek"],
  ["ark", "agk"],
  ["\\b(M|m)oet\\b", "$1ot"],
  ["nair", "nèâh"],
  ["neme\\b", "neime"],
  ["nemi", "neimi"],
  ["nce", "nse"],
  ["\\b(N|n)u\\b", "$1âh"],
  ["ny", "ni"],
  ["\\bmad", "med"],
  ["(?<![v])(a|o)(rdt|rd)(?![eû])", "$1gt"],
  ["ord(e|û)", "ogd$1"],
  ["(N|n)(|o)od", "$1aud"],
  ["nirs\\b", "nieâhs"],
  ["l(f|k|m|p)(?![aeiroul])", "lle$1"],
  ["(a|e|o)lk(?![ao])", "$1llek"],
  ["(F|f)olleklore", "$1olklore"],
  ["o(c|k)a", "auka"],
  ["(?<![o])oms", "omps"],
  ["(T|t)one(e|i)", "$1aunei"],
  ["on(a|i)", "aun$1"],
  ["hore", "hoâhre"],
  ["org(?![i])", "orrag"],
  ["orp", "orrep"],
  ["mor\\b", "moâh"],
  ["\\borg", "oâhg"],
  ["Over(?![ei])", "Auvâh"],
  ["(?<![z])over(?![ei])", "auvâh"],
  ["o(v|z)e", "au$1e"],
  ["olop", "ollop"],
  ["i(p|P)hone", "aaifaun"],
  ["Iphone", "Aaifaun"],
  ["emo(?![e])", "eimau"],
  ["(?<![gz ])o(b|d|g|k|l|m|n|p|s|t|v)(i|e|o|au)", "au$1$2"],
  ["\\bo(l|p)(i|e)", "au$1$2"],
  ["O(b|d|g|k|l|m|p|s|t|v)(i|e)", "Au$1$2"],
  ["\\bout", "âht"],
  ["\\bOut", "Âht"],
  ["\\b(V|v)er\\b", "$1eâh"],
  ["ederta", "edâhta"],
  ["(D|d)ert(?![u])", "$1eâht"],
  ["\\b(D|d)er\\b", "$1eâh"],
  ["der(?![dehianrouèt])", "dâh"],
  ["\\b(P|p|T|t)er\\b", "$1eâh"],
  ["(Z|z)auver\\b", "$1auveâh"],
  ["ergi", "egi"],
  ["(?<![ io])er\\b", "âh"],
  ["eiker(g|h)", "eikâh$1"],
  ["orm", "orrum"],
  ["(P|p)er(?![aeirt])", "$1âh"],
  ["(P| p)o(^st)", "$1au$2"],
  ["p ik\\b", "ppik"],
  ["ppen", "ppe"],
  ["popu", "paupe"],
  ["(p|P)ro(?![oefkns])", "$1rau"],
  ["(p|P)rofe", "$1raufe"],
  ["ersch", "esch"],
  ["(A|a)rme", "$1rreme"],
  ["re(s|tr)o", "rei$1o"],
  ["palè", "pelè"],
  ["(R|r)elax", "$1ieleks"],
  ["(R|r)estâhrant", "$1esterant"],
  ["(R|r)esu", "$1eisu"],
  ["rants\\b", "rans"],
  ["rigste", "ragste"],
  ["rod", "raud"],
  ["(r|R)ou", "$1oe"],
  ["(a|o)rt", "$1gt"],
  ["([Rr])o(?=ma)", "$1au"],
  ["inds", "ins"],
  ["seque", "sekwe"],
  ["sjes\\b", "ssies"],
  ["(S|s)hop", "$1jop"],
  ["stje\\b", "ssie"],
  ["st(b|d|g|h|j|k|l|m|n|p|v|w|z)", "s$1"],
  ["(S|s)ouv", "$1oev"],
  ["(?<![gr])st\\b", "s"],
  ["stf", "sf"],
  ["tep\\b", "teppie"],
  ["té\\b", "tei"],
  ["tion", "sion"],
  ["(d|t)je\\b", "$1sje"],
  ["\\b(T|t)o\\b", "$1oe"],
  ["(p|t)o\\b", "$1au"],
  ["toma", "tauma"],
  ["(T|t)ram", "$1rem"],
  ["quaran", "karre"],
  ["ua", "uwa"],
  ["(J|j)anu", "$1anne"],
  ["ùite\\b", "ùitûh"],
  ["(u|ù)igt\\b", "$1ig"],
  ["(U|u)ren", "$1re"],
  ["ùidâh\\b", "ùiâh"],
  ["unch", "uns"],
  ["anch", "ansj"],
  ["(?<![u])urg", "urrag"],
  ["(?<![u])urs", "ugs"],
  ["uur", "uâh"],
  ["ur(f|k)", "urre$1"],
  ["(T|t)eam", "$1iem"],
  ["ntures", "ntjâhs"],
  ["ultur", "ulter"],
  ["(?<![Ss])tu(?![âfkurst])", "te"],
  ["\\bvan je\\b", "vajje"],
  ["\\bvan (het|ut)\\b", "vannut"],
  ["\\b(V|v)ege(?![lz])", "$1eige"],
  ["vert\\b", "vâht"],
  ["([Vv])er(?![aeèfrious])", "$1e"],
  ["([Vv])er(sl|sta)", "$1e$2"],
  ["vaka", "veka"],
  ["vard", "vâh"],
  ["voetbal", "foebal"],
  ["we er ", "we d'r "],
  ["\\ber\\b", "d'r"],
  ["\\bEr\\b", "D'r"],
  ["(I|i)n je\\b", "$1jje"],
  ["wil hem\\b", "wil 'm"],
  ["(W|w|H|h)ee(t|l)", "$1ei$2"],
  ["Young", "Jong"],
  ["young", "jong"],
  ["yo", "jau"],
  ["Yo", "Yau"],
  ["\\b(Z|z)ee", "$1ei"],
  ["eep", "iep"],
  ["\\b(Z|z)ult\\b", "$1al"],
  ["z'n", "ze"],
  ["\\bzich\\b", "ze ège"],
  ["z(au|o)'n", "zaun"],
  ["\\bzegt\\b", "zeg"],
  ["(z|Z)(o|ó)(?![cenr])", "$1au"],
  ["'t", "ut"],
  ["derr", "dèrr"],
  ["Nie-westegse", "Niet westagse"],
  ["us sie", "us-sie"],
  ["\\bThe Hague\\b", "De Heek"],
  ["Krowne", "Kraun"],
  ["social media", "sausjel miedieja"],
  ["\\b(D|d)em", "$1eim"],
  ["ssio", "ssiau"],
  ["sol(?![l])", "saul"],
  ["aine", "ène"],
  ["tain", "tein"],
  ["terna", "tena"],
  ["(?<![eèuoin])gel\\b", "sjel"],
  ["ingel\\b", "ingol"],
  ["ign", "inj"],
  ["down", "dâhn"],
  ["lock", "lok"],
  ["(?<![s])sis(?![i])", "sus"],
  ["COVID", "KAUVID"],
  ["stgong>", "strong>"],
  ["kute;", "cute;"],
  ["&ksedil;", "&ccedil;"],
  ["lie>", "li>"]
];

// the word boundary '\b' in javascript doesn't work the same as in the original project, so replace it iwth something that will work
const boundaryCharacters = "\\s.,:;\\-_?!";
const boundaryStart = `(?<=^|[${boundaryCharacters}])`;
const boundaryEnd = `(?=$|[${boundaryCharacters}])`;
const translationReplacements = originalTranslationReplacements.map((r) => {
  const regex = r[0]
    .replace(/^\\b/g, boundaryStart)
    .replace(/\\b$/g, boundaryEnd);
  return [regex, r[1]];
});

function checkNodeVersion() {
  const match = process.version.match(/^v(\d+)/);
  if (!match) {
    return;
  }
  const majorVersion = Number(match[1]);
  if (majorVersion < 20) {
    throw new Error("This package requires Node.js v20 or higher");
  }
}

function translate(dutch: string) {
  checkNodeVersion();

  if (!dutch) {
    return dutch;
  }

  return translationReplacements.reduce((result, replacement) => {
    try {
      return result.replace(new RegExp(replacement[0], "gm"), replacement[1]);
    } catch {
      return result;
    }
  }, dutch);
}

function getHits(dutch: string) {
  if (!dutch) {
    return [];
  }

  const result: [string, string, string][] = [];
  translationReplacements.reduce((r, replacement) => {
    try {
      const original = r;
      const haags = original.replace(
        new RegExp(replacement[0], "gm"),
        replacement[1]
      );
      const didHit = original.toLowerCase() !== haags.toLowerCase();

      if (didHit) {
        result.push([replacement[0], replacement[1], haags]);
      }
      return haags;
    } catch {
      return r;
    }
  }, dutch);

  return result;
}

function showHits(dutch: string) {
  for (const r of getHits(dutch)) {
    console.log(
      "\x1b[32m",
      `[${r[0]}]`,
      "\x1b[0m-\x1b[33m",
      `[${r[1]}]`,
      "\x1b[0m:",
      r[2]
    );
  }
}

module.exports = {
  showHits,
  translate,
};
